Repository itgalaxy/webfont, pull requests merged in 2020-09, with the labels that each got.

#209 fix(deps): fix/sort deps and scripts after `npm audit fix`
  package-lock.json
  package.json
Labels: dependencies, security

#212 docs(pull request template): add PR template
  .github/pull_request_template.md
Labels: community, documentation

#211 build: drop support for Node.js 8 (EOL)
  .gitattributes
  .travis.yml
  appveyor.yml
  package.json
Labels: build, ci, dependencies

#213 chore(dependabot): configure dependabot
  .github/dependabot.yml
Labels: dependencies

#207 docs(code_of_conduct): add Code of Conduct
  CODE_OF_CONDUCT.md
Labels: community

#220 fix(deps): sort/upgrade dependencies after npm audit fix
  package-lock.json
  package.json
Labels: dependencies, security

#223 chore: update `docs/bug-report` with main branch content
  .gitattributes
  .github/dependabot.yml
  .github/pull_request_template.md
  .snyk
  .travis.yml
  CODE_OF_CONDUCT.md
  appveyor.yml
  package-lock.json
  package.json
Labels: sync

#206 docs(bug_report): add bug report template [WIP]
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: ci running, community, documentation

#224 docs(contributing): add CONTRIBUTING info
  CONTRIBUTING.md
Labels: ci running, community, documentation

#199 Respect `formats` option when using external config
  src/__tests__/fixtures/configs/.webfontrc-with-custom-formats
  src/__tests__/standalone.test.js
  src/standalone.js
Labels: bug, ci passed

#225 fix(deps): pin/upgrade eslint dependencies, fix some errors
  package-lock.json
  package.json
  src/__tests__/standalone.test.js
  src/cli.js
  src/standalone.js
Labels: dependencies
